apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rocketmq
spec:
  replicas: 1
  template:
    metadata:
     labels:
       app: rocketmq
    spec:
      containers:
      - name: broker
        image: arilot/rocketmq-broker:4.3.0-k8s
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 10909
          - containerPort: 10911
        volumeMounts:
          - mountPath: /opt/logs
            name: broker-pv
            subPath: logs
          - mountPath: /opt/store
            name: broker-pv
            subPath: store
      - name: namesrv
        image: arilot/rocketmq-namesrv:4.3.0-k8s
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 9876
        volumeMounts:
          - mountPath: /opt/logs
            name: namesrv-pv
            subPath: logs
          - mountPath: /opt/store
            name: namesrv-pv
            subPath: store
      volumes:
      - name: broker-pv
        persistentVolumeClaim:
          claimName: rocketmq-broker-pv
      - name: namesrv-pv
        persistentVolumeClaim:
          claimName: rocketmq-namesrv-pv
      # nodeSelector:
      #      rocketmq: "on"
