apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rocketmq
spec:
  replicas: 1
  template:
    metadata:
     labels:
       app: rocketmq
    spec:
      containers:
      - name: broker
        image: arilot/rocketmq-broker:4.3.0-k8s
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 10909
          - containerPort: 10911
        volumeMounts:
          - mountPath: /opt/logs
            name: brokeroptlogs
            subPath: logs
          - mountPath: /opt/store
            name: brokeroptstore
            subPath: store
      - name: namesrv
        image: arilot/rocketmq-namesrv:4.3.0-k8s
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 9876
        volumeMounts:
          - mountPath: /opt/logs
            name: namesrvoptlogs
            subPath: logs
          - mountPath: /opt/store
            name: namesrvoptstore
            subPath: store
      volumes:
      - name: brokeroptlogs
        persistentVolumeClaim:
          claimName: broker-pv
      - name: brokeroptstore
        persistentVolumeClaim:
          claimName: broker-pv
      - name: namesrvoptlogs
        persistentVolumeClaim:
          claimName: namesrv-pv
      - name: namesrvoptstore
        persistentVolumeClaim:
          claimName: namesrv-pv
      # nodeSelector:
      #      rocketmq: "on"
